scripts/gravisuite.zs

Gravisuite glass fiber cable replacement recipes.

Gravisuite glass fiber cable replacement recipes

---

config/enderio/EnderIO.cfg
scripts/enderio.zs

Raised the number of eIO conduits crafted from 4 to 6. Resolves #216

EnderIO Conduits

---

config/OpenBlocks.cfg
scripts/bigreactors.zs
scripts/extrautilities.zs
scripts/forestry.zs
scripts/jabba.zs
scripts/openblocks.zs
scripts/stevesworkshop.zs

I think its better to enable the items, remove the recipes and add a tooltip to it than simply disabling items because it is annoying if you cannot find an item in NEI and don't know if its disabled or you misspelled it.

added tooltip to disabled items

---

scripts/tcaspects.zs

fix for https://github.com/JasonMcRay/InfiTech-1.7/issues/447

fix for wand cap exploit

---

config/headcrumbs.cfg

December Patreon

---

scripts/railcraft.zs

remove Steam Oven

---

scripts/gt_ic2.zs

added disabled tooltips for industrialcraft

---

config/GregTech/Recipes.cfg
scripts/thaumcraft.zs

Just a couple of last minute tweaks for balance and forgotten things

Thaumcraft tweak

---

scripts/thaumcraft.zs

Broken Pure Love research

---

scripts/stevescarts2.zs

closes this https://github.com/JasonMcRay/InfiTech-1.7/issues/521

recipe conflict fix for minecart / standard hull

---

scripts/malisis.zs
scripts/railcraft.zs
scripts/thaumcraft.zs
scripts/thaumcraftenchantments.zs

Fixes thaumcraft complexities, cinderpearls, shunting wire, wire support frame, and malisis door clash. Also lowers node transducer and sorting core to be more reasonable in price.

General minor fixes

---

scripts/forestry.zs

fix for https://github.com/JasonMcRay/InfiTech-1.7/issues/533
@Blood-Asp is that a problem in gregtech?
The other recipes with wood pulp and the carpenter work.

letter recipe fix

---

scripts/gt_ic2.zs

vanilla saplings cannot be made into plantballs

---

scripts/vanilla.zs

If you change the diamond armor then you should also change the diamond tools.
https://github.com/JasonMcRay/InfiTech-1.7/commit/7181f4af36ff9d8eb3ea84d4a3e71ac955eb8152#diff-366ce481c1bb826b9288093483a1bfe3R82

diamond tools

---

scripts/thaumcraft.zs

Made the node transducer a bit easier to craft. Added a SEEECRET recipe for the node transducer. It should take players SEVERAL SECONDS to discover it.

Node Transducer recipe changes

---

scripts/thaumcraft.zs

Warp lowered

---

scripts/thaumcraft.zs

Change thaumcraft prereqs

---

scripts/thaumcraft.zs

Readd TC charcoal fabrication

---

scripts/thaumcraft.zs

Remove IBF recipes from NEI

---

scripts/thaumcraft.zs

For #585 
Confirmed it is actually possible to research it, despite needing even more aspects than normal naquadah transmutation.

Fix naquadah transmutation

---

scripts/thaumcraftclusters.zs

Add iron cluster + calcite recipe

---

scripts/thaumcraft.zs

Change TK foci to red garnet

---

config/gendustry/bees.cfg
scripts/notthebees.zs

This time its ours, processing is nerfed.

Added Osmium Bee

---

scripts/thaumcraft.zs

Fix steel transmutation

---

scripts/chisel.zs

Makes it possible to chisel between IC2 and PR basalt cobblestone

Add basalt chiseling

---

scripts/railcraft.zs

* Doubles track recipe output 
* Adds alternate recipe for rails, half output with stick instead of wood tie
* Replaces wooden ties with planks in track recipes

Make wooden rails easier to craft and pre-tech

---

scripts/stevescarts2.zs

Moves them to MV with the rest of the automated wood chopping methods

Move Steve's Carts Wood Cutter to MV

---

scripts/SGCraft.zs

This has been bothering me now way too long because its not called stargate controller its a DHD. http://stargate.wikia.com/wiki/Dial_Home_Device

rename Stargate Controller to DHD (Dial Home Device)

---

config/StorageDrawers.cfg

https://www.youtube.com/watch?v=Vp7OS_2RaNU

prevent storage drawer exploit

---

config/GregTech/Recipes.cfg
config/IC2.ini
scripts/gt_ic2.zs

Rebalance tin can recipe

---

scripts/vanilla.zs

XU stabilization ritual requires vanilla ores

Add GT Ore to Vanilla Ore exchange

---

scripts/tcaspects.zs

Just leave this till the next update or something, I'll throw any other extra aspect changes in here if it's unmerged.

More aspect changes

---

config/gendustry/bees.cfg

Certus bee wasn't recognising AE2 certus block via oredict, typo in platinum bee block requirement.

Fix certus and platinum bee

---

scripts/thaumcraft.zs

For only one extra aqua no longer water your crops again! or something.

Upgrade TC farmland recipes to garden soil

---

scripts/thaumcraftclusters.zs

Clusters are currently better than bees for tungsten output with tungstate.

Halve tungstate cluster output

---

config/ThaumicTinkerer.cfg
scripts/ttkami.zs

Enable KAMI

---

config/GregTech/Recipes.cfg

Disable kami shards in generator

---

scripts/thaumcraft.zs
scripts/thaumcraftclusters.zs
scripts/ttkami.zs

Conceal unconcealed custom researches

---

scripts/hqm.zs

Fixes the QDS recipe to not consume the book, as it was originally intended to be.

Fix QDS recipe

---

config/OpenComputers.cfg

workaround for https://github.com/MightyPirates/OpenComputers/issues/1908

computer crash (ingame computer)

---

scripts/thaumcraft.zs

Re-add alumentum from charcoal recipe

---

config/immibis.cfg

Fuel values set to 67.5 * burn time

Add Solid Super Fuel as Dim Anchor fuel

---

scripts/storagedrawers.zs

Duct Tape can be made in the assembler, so why not Packing Tape?

Add Assembler Recipe for Drawer Packing Tape

---

scripts/tcaspects.zs

fix https://github.com/JasonMcRay/InfiTech-1.7/issues/842

flint and steel fix

---

scripts/AE2.zs

I mean really? The staff is pointing at the top right corner not the left corner.

correct orientation of charged staff recipe

---

scripts/AE2.zs

Reverts JasonMcRay/InfiTech-1.7#849

Revert "correct orientation of charged staff recipe"
