- config/gendustry/bees.cfg
- config/gendustry/overrides/tuning.cfg
Raised bee products chance.
Radioactive bee now produces DOB Comb, which when centrifuged will give low chance of product.
lowered mutation chances of Organic, Gem, Alloy and Thaumic Bee types. Raised mutation chance of Metalic and Metalic Rare bees.
Moved Gendustry machines from HV to MV (only power tier change)
Closes #380
> Gendustry overhaul

- scripts/extrautilities.zs
I moved the bcquarry -> enderquarry into the qed because its confusion people that its shown on the first page of NEI.
There is someone asking about this on the forum every week so it would be better if both recipes are on the same page.
> moved bcquarry -> enderquarry recipe into qed

- scripts/thaumcraft.zs
For use with thaumcraft notably, prevents needing 9 nether stars before the creation of nether star plates for the warding focus.
> Add nether star dust to nether star plate compression

- config/buildcraft/objects.cfg
- scripts/gt_ic2.zs
- scripts/openblocks.zs
I'm not sure how many people have realized this yet, but you can easily circumvent the annoying need for black carpet for tin cable by using one of the three paint brushes. The OpenBlocks paintbrush has a  questionable 25 uses, the IC2 painter has a predictable 32 uses, and the BC paintbrush has an astounding 64 uses per dye. The BC paintbrush was immediately disabled. Since the OB paintbrush is the only one that can accept custom dye colors, I just gregged the recipe for it and the IC2 painter. This means you now have to at least have LV tech to make them, meaning you have to make at least some of the black carpet the hard way. All three of the brushes could color GT (and IC2) cables, BC pipes, RC tank walls, and AE2 cables, so there was no conflict there.
> Fix paint exploit

- scripts/thaumcraftclusters.zs
For #585
U-235 ore doesn't actually generate, it was a misunderstanding while making the scripts.
> Remove U-235 Clusters

- scripts/magicbees.zs
It looks like all MagicBees combs (except mundane comb) are missing "beeComb" OreDict name.
Sure this is a mod bug and should be fixed in MagicBees, but I can't wait and I'm too lazy to setup every single item in my Storage Bus ^_^
This commit is a simple workaround, and report to mod developers as follows: MagicBees/MagicBees#136
> MagicBees combs missing OreDict name

- config/forestry/apiculture.cfg
- config/gendustry/Bees.en_US.lang
- config/gendustry/bees.cfg
Several bees exist from magical bees that directly give nuggets and for which a custom variant already exists, this removes them. It also removes cobalt for which we do not have an equivalent bee, but nickel combs already work to purifying cobaltite.
> Disable overlapping MB resource bees

- scripts/pneumaticcraft.zs
Makes PC fuels 10x less powerful as normal furnace fuels, making them not 10x more power output than GT LPG. Only way to achieve huge burn time is now in PC liquid generators.
> Lower burntime of PneumaticCraft fuels

- config/enderio/SAGMillRecipes_User.xml
- scripts/enderio.zs
Makes it compatible with all GT ores, and as a machine that produces high amounts of byproducts but low amounts of the primary output.
> Redo SAG Mill recipes

- scripts/gt_ic2.zs
The gregtech and industrialcraft2 uran / plutonium is the same stuff but without oredict which is now fixed.
@Blood-Asp I think this is a problem with gregtech.
> uran / plutonium fix

- config/GregTech/MachineStats.cfg
Egg - 500EU/t
reason the value is 1/100 in the config is because of current bug where there is set multiplier to 100x.
Will be raised after the bug is fixed in GT.
For reference: https://github.com/Blood-Asp/GT5-Unofficial/issues/486
> Lowered absorber power production

- config/ExtraUtilities.cfg
- scripts/extrautilities.zs
Just edited the extra utilities config and the extra utilities script to enable the void dimension that extra utilities adds, but **not** allow users access to the deep dark.
Was considering changing the last millennium portal recipe to the QED, but it's just a void dimension so I left it as the default recipe.
> Enabling the Last Millennium Dimension.

- scripts/AE2.zs
Unifies it with standard modified wireless recipes as opposed to being only MV to the normal wireless HV.
> Modify wireless crafting terminal recipe

- scripts/extrautilities.zs
I don't think the recipe for the portal to the last millenium should be in the QED because its a void dimension and people should be able to build there from the start (it is only deco) and not after already being HV age, having the best ebf and a vacuum freezer.
> moved Portal to Last Millenium recipe out of the QED

- config/SGCraft.cfg
In the series its only transparent when you look at it from behind but from the front its always opaque.
It would also "fix" those kind of glitches.
with this change it would look like this
> opaque event horizon

- config/enderio/SAGMillRecipes_User.xml
Lowers base chance rates, increases grinding ball chance rates proportionally, nerfs grinding ball material/power usage
Now requires dark steel to nearly match previous non-grinding ball rates, dark steel/titanium/naquadah alloy/neutronium new grinding ball tiers.
> Nerf SAG Mill

- scripts/buildcraft.zs
Wood, Stone, Cobble, and Sandstone pipes can now be crafted in an Assembler, as an alternative to hand tools.
Allows LP to make its own pipes without wearing out hand tools in a Logistics Crafting Table.
> Add Assembler recipes for remaining BC pipes

- config/BiblioCraft.cfg
Not sure when we lost this, but I don't see any reason not to add this back.
> Adding (warded) jars back to bibliocraft potion shelves

- scripts/storagedrawers.zs
A minor convenience, especially given that the Drawer isn't as useful for storing metals due to Blocks being made in a Compressor and Nuggets being made in a Furnace.
> Allow Industrial Credits in Compacting Drawer

- scripts/enderio.zs
The item buffer is basically a item conduit with a 9 slot inventory that can extract 1 full stack at a time and it doesn't make sense that you can make this long before you can make the item conduits.
before:
after:
> change item buffer recipe

- config/SGCraft.cfg
This stops chevrons from moving. Seriously they are fixed in position they could never ever move in the series.
> prevent moving chevrons
